{
  "gameEventBehavior":  {
    "AIMLESS_KICK":  "BEHAVIOR_ACCEPT_MAJORITY",
    "ATTACKER_DOUBLE_TOUCHED_BALL":  "BEHAVIOR_ACCEPT_MAJORITY",
    "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA":  "BEHAVIOR_ACCEPT_MAJORITY",
    "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BALL_LEFT_FIELD_GOAL_LINE":  "BEHAVIOR_IGNORE",
    "BALL_LEFT_FIELD_TOUCH_LINE":  "BEHAVIOR_IGNORE",
    "BOT_CRASH_DRAWN":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_CRASH_UNIQUE":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_DRIBBLED_BALL_TOO_FAR":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_DROPPED_PARTS":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_HELD_BALL_DELIBERATELY":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_INTERFERED_PLACEMENT":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_KICKED_BALL_TOO_FAST":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_PUSHED_BOT":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_TIPPED_OVER":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOT_TOO_FAST_IN_STOP":  "BEHAVIOR_ACCEPT_MAJORITY",
    "BOUNDARY_CROSSING":  "BEHAVIOR_ACCEPT_MAJORITY",
    "DEFENDER_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT_MAJORITY",
    "DEFENDER_TOO_CLOSE_TO_KICK_POINT":  "BEHAVIOR_ACCEPT_MAJORITY",
    "GOAL":  "BEHAVIOR_ACCEPT_MAJORITY",
    "INVALID_GOAL":  "BEHAVIOR_ACCEPT_MAJORITY",
    "KEEPER_HELD_BALL":  "BEHAVIOR_ACCEPT_MAJORITY",
    "NO_PROGRESS_IN_GAME":  "BEHAVIOR_ACCEPT_MAJORITY",
    "PENALTY_KICK_FAILED":  "BEHAVIOR_ACCEPT_MAJORITY",
    "PLACEMENT_SUCCEEDED":  "BEHAVIOR_ACCEPT_MAJORITY",
    "POSSIBLE_GOAL":  "BEHAVIOR_ACCEPT",
    "TOO_MANY_ROBOTS":  "BEHAVIOR_ACCEPT_MAJORITY"
  },
  "autoRefConfigs":  {
    "Robocup-SSL-China AutoRef v1.0@10.95.52.13":  {
      "gameEventBehavior":  {
        "AIMLESS_KICK":  "BEHAVIOR_ACCEPT",
        "ATTACKER_DOUBLE_TOUCHED_BALL":  "BEHAVIOR_ACCEPT",
        "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_GOAL_LINE":  "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_TOUCH_LINE":  "BEHAVIOR_ACCEPT",
        "BOT_CRASH_DRAWN":  "BEHAVIOR_ACCEPT",
        "BOT_CRASH_UNIQUE":  "BEHAVIOR_ACCEPT",
        "BOT_DRIBBLED_BALL_TOO_FAR":  "BEHAVIOR_ACCEPT",
        "BOT_DROPPED_PARTS":  "BEHAVIOR_ACCEPT",
        "BOT_HELD_BALL_DELIBERATELY":  "BEHAVIOR_ACCEPT",
        "BOT_INTERFERED_PLACEMENT":  "BEHAVIOR_ACCEPT",
        "BOT_KICKED_BALL_TOO_FAST":  "BEHAVIOR_ACCEPT",
        "BOT_PUSHED_BOT":  "BEHAVIOR_ACCEPT",
        "BOT_TIPPED_OVER":  "BEHAVIOR_ACCEPT",
        "BOT_TOO_FAST_IN_STOP":  "BEHAVIOR_ACCEPT",
        "BOUNDARY_CROSSING":  "BEHAVIOR_ACCEPT",
        "DEFENDER_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "DEFENDER_TOO_CLOSE_TO_KICK_POINT":  "BEHAVIOR_ACCEPT",
        "GOAL":  "BEHAVIOR_ACCEPT",
        "INVALID_GOAL":  "BEHAVIOR_ACCEPT",
        "KEEPER_HELD_BALL":  "BEHAVIOR_ACCEPT",
        "NO_PROGRESS_IN_GAME":  "BEHAVIOR_ACCEPT",
        "PENALTY_KICK_FAILED":  "BEHAVIOR_ACCEPT",
        "PLACEMENT_SUCCEEDED":  "BEHAVIOR_ACCEPT",
        "POSSIBLE_GOAL":  "BEHAVIOR_ACCEPT",
        "TOO_MANY_ROBOTS":  "BEHAVIOR_ACCEPT"
      }
    }
  },
  "teams":  [
    "宁波大学 NBUnited-1",
    "宁波大学 NBUnited-2",
    "宁波大学 NBUnited-3",
    "宁波工程学院 下标越界",
    "宁波工程学院 内存溢出",
    "宁波工程学院 编译错误",
    "宁波工程学院 访问超时",
    "浙大城市学院 Debug2",
    "浙大城市学院 Debug4",
    "浙大城市学院 debug3",
    "浙大城市学院 浙江绿城FC 10086队",
    "浙大宁波理工学院 裕达足球1队",
    "浙大宁波理工学院 裕达足球2队",
    "浙大宁波理工学院 裕达足球3队",
    "浙大宁波理工学院 裕达足球4队",
    "浙江大学 ZJUNlict_1",
    "浙江大学 ZJUNlict_2",
    "浙江水利水电学院 你说的什么都队",
    "浙江水利水电学院 玛卡巴卡队",
    "浙江水利水电学院 破浪队",
    "浙江纺织服装职业技术学院 LML",
    "湖州师范大学 人民民组",
    "湖州师范大学 天天向上组",
    "湖州师范大学 普通的组",
    "湖州师范大学 非常队",
    "宁波大学 NBUnited-Tech1",
    "宁波大学 NBUnited-Tech2",
    "宁波大学 NBUnited-Tech3",
    "宁波大学 NBUnited-Tech4",
    "宁波大学科学技术学院 value_is_nil",
    "宁波大学科学技术学院 不儿，我球去哪了",
    "宁波大学科学技术学院 我们真能进球嘛",
    "宁波工程学院 下标越界_404",
    "宁波工程学院 内存溢出_404",
    "宁波工程学院 编译错误_404",
    "宁波工程学院 访问超时_404",
    "浙大宁波理工学院 裕达足球1队",
    "浙大宁波理工学院 裕达足球2队",
    "浙大宁波理工学院 裕达足球3队",
    "浙大宁波理工学院 裕达足球4队",
    "浙江大学 ZJUNlict2",
    "浙江大学 zjunlict3",
    "浙江水利水电学院 NEOS队",
    "浙江水利水电学院 启航队",
    "浙江水利水电学院 好运降临队",
    "湖州师范大学 Tonny带水组",
    "湖州师范大学 不普通的组",
    "湖州师范大学 人民民组",
    "湖州师范大学 天天向上组",
    "SPbUnited-1",
    "SPbUnited-2"
  ],
  "autoContinue":  true
}